### ISSUE TITLE
Support `docker volume delete`

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1511]

**Comment by matthewavery** [comment]
This should be resolved. I believe this was among the first of the volume calls to be implemented. I am now hand testing everything to make sure that it works. I will look at writing integration tests now since mike got Volume Create tests running.

**Comment by mdubya66** [comment]
@matthewavery this is an Epic that seems to have two issues remaining, #1508 and #1510 It's not resolved until those are.

**Comment by fdawg4l** [comment]
@matthewavery Sort of.  VolumeDestroy on the vsphere side will return an error "TBD. Not supported yet".  FYI.  If you have the docker client -> docker server -> pl stuff done, then I'm ok closing this issue if we can create an issue to capture filling in the functionality on the vsphere side.

**Comment by mdubya66** [comment]
Moving to Doc for GA as that is the only remaining issue.

**Comment by stuclem** [comment]
Doc is done. Closed https://github.com/vmware/vic/issues/1521.

**Comment by matthewavery** [comment]
@fdawg4l This is ready for closing right?

**Comment by fdawg4l** [comment]
Yup!
