### ISSUE TITLE
Remove CIDR requirement from container network

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1741]
**VIC Version:**

0.1 / master / 3190

This is opened based on a suggestion in https://github.com/vmware/vic/issues/1542

It doesn't make sense to me that the gateway for the container network would need CIDR notation. Typically a gateway is simply a single ip address.

In the example below, if I try to specify just an ip address for the gateway, which i think is what most people would do, I get an error. 
```
root@photon-NaTv5i8IA [ /workspace/vic ]# ./vic-machine-linux create --bridge-network Bridge-DPG --image-datastore isilion-nfs-01 -t 'administrator@vsphere.local:VMware123!@10.27.51.103' --compute-resource Mgmt --container-network con-nw:con-nw --container-network-gateway con-nw:192.168.100.1  --container-network-dns con-nw:192.168.100.254 --container-network-ip-range con-nw:192.168.100.2-253
Error parsing container network parameter con-nw:192.168.100.1: invalid CIDR address: 192.168.100.1
```

I must specify the gateway in CIDR format, which doesn't make a lot of sense to me.

```
root@photon-NaTv5i8IA [ /workspace/vic ]# ./vic-machine-linux create --bridge-network Bridge-DPG --image-datastore isilion-nfs-01 -t 'administrator@vsphere.local:VMware123!@10.27.51.103' --compute-resource Mgmt --container-network con-nw:con-nw --container-network-gateway con-nw:192.168.100.1/24  --container-network-dns con-nw:192.168.100.254 --container-network-ip-range con-nw:192.168.100.2-253
```

**Expected behavior:**
I should be able to specify container network gateway as IP address.

**Actual behavior:**
I must specify container network gateway as IP address with CIDR.

**Comment by lgayatri** [comment]
Is this issue resolved in the Dec'2016 released bits?

**Comment by mdubya66** [comment]
No. it is resolved in our master. @lgayatri

**Comment by andrewtchin** [comment]
This issue isn't resolved yet the container network gateway is parsed differently from the other gateway values where the CIDR requirement was removed. 
`cmd/vic-machine/create/create.go`

**Comment by hickeng** [comment]
Put this as medium as consistency is important. I _think_ it was done this way so that entire subnet ranges could be specified without using `--container-network-ip-range` but agree with consistency. The subnet still needs to be expressed and the IP range is a better fit. Will require custom parsing however.

**Comment by dbarkelew** [comment]
FYI: A customer that wanted to use /24 on a custom bridge network today. Not a blocker since the services in the overlapped IP range do not need to communicate to any container services and are moving forward with /16 for now.
