### ISSUE TITLE
Portmapping not working with v0.6.0

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#2388]
[container-logs(1).zip](https://github.com/vmware/vic/files/482401/container-logs.1.zip)

**VIC Version:**

0.1 / master / 4890

**Code**

```ts

Tried a simple test with nginx running on VIC

Looks like the port is not getting mapped through.

Could be the same as https://github.com/vmware/vic/issues/2354

Attaching the logs asap.

```

**Expected behavior:**

I would have expected to connect to the nginx web server through VIC. I think this worked in the passed so this seems like a regression.

**Actual behavior:**

Cannot connect to nginx web server running in a container in VIC.

**Comment by hmahmood** [comment]
```
root@virtual-container-host [ ~ ]# arp -a
? (172.16.0.2) at <incomplete> on bridge
esxi-hp-08.rainpole.com (10.27.51.8) at 98:4b:e1:04:65:12 [ether] on external
? (10.27.51.254) at 58:8d:09:ee:68:80 [ether] on external
? (10.27.51.103) at 00:50:56:b5:5a:ec [ether] on external
dc01.rainpole.com (10.27.51.252) at 00:0c:29:52:3a:9d [ether] on external
? (10.27.51.9) at e4:11:5b:aa:8e:42 [ether] on external
esxi-hp-10.rainpole.com (10.27.51.10) at e4:11:5b:ab:bb:dc [ether] on external
```

**Comment by hmahmood** [comment]
See https://github.com/vmware/vic/issues/2316

**Comment by cormachogan** [comment]
You are right - if the containers are on the same host, they can talk over the bridge n/w, but if they are on different hosts, they cannot. Let me look into this some more.

**Comment by cormachogan** [comment]
Yep - VLAN/uplink settings on the hosts connected to the DVS. All working now! Thanks @hmahmood for the direction.

**Comment by stuclem** [comment]
This is fixed. Removing kind/note.

**Comment by Sevyls** [comment]
> Yep - VLAN/uplink settings on the hosts connected to the DVS. All working now! Thanks @hmahmood for the direction.

Was this fixed? In VIC 1.3 we still see the problem.

**Comment by Sevyls** [comment]
> Yep - VLAN/uplink settings on the hosts connected to the DVS. All working now! Thanks @hmahmood for the direction.

Was this fixed to work with different hosts for VCH and container to work now?
We still see this issue in VIC 1.3, when containers are running on different hosts.

**Comment by yuyangbj** [comment]
@Sevyls if your VCH and container VM are in different host, you need to make sure your VLAN setting for your distributed port group (for example bridge) is supported by your physical network.
