### ISSUE TITLE
Upon HA failover, the VCHs running on the rebooted host, continue to stay in OFF state

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#6323]
This test was done to check the resiliency of VCH.

Build: v1.2.0-rc5
Steps:
1. VC with HA,DRS cluster, added few ESX hosts and created 50 VCHs and 2500 containers
2. Rebooted ESX host where I have few VCHs and containers running
3. As HA was enabled, all VCHs and containers got restarted on other hosts
4. Admiral shows these VCHs as OFF
![image](https://user-images.githubusercontent.com/25006749/30428197-507d54a4-9970-11e7-9c5c-ea53575fd72f.png)
5. POrt layer is not running
![image](https://user-images.githubusercontent.com/25006749/30428836-b47a7aa2-9972-11e7-8401-bbe59ec03137.png)
Logs from VCH are attached:

**Comment by lgayatri** [comment]
[container-logs (1).zip](https://github.com/vmware/vic/files/1302851/container-logs.1.zip)

**Comment by lgayatri** [comment]
@mhagen-vmware @anchal-agrawal @andrewc-vmware @mlh78750 @sergiosagu

**Comment by mhagen-vmware** [comment]
Thanks @lgayatri for the logs.  Can you attempt to manually power on as well and see if the VCHs will function after that?

**Comment by lgayatri** [comment]
On the same testbed(which was left untouched after this bug was reported) the VCHs are back to ON state automatically. Container power On also working. May be admiral takes a while to sync up.

![image](https://user-images.githubusercontent.com/25006749/30558428-f94ceb06-9cce-11e7-8237-a612007d4b6c.png)

**Comment by sergiosagu** [comment]
> May be admiral takes a while to sync up.

This will be addressed in https://github.com/vmware/vic-planning/issues/74.

**Comment by lgayatri** [comment]
@sergiosagu , can I expect the fix is in for this issue?

**Comment by mdubya66** [comment]
The issue of admiral sync time has been resolved in 1.3 and should have been there in RC2. vic-planning#74

**Comment by sergiosagu** [comment]
@lgayatri - @mdubya66 is right. Have you still experienced the issue with RC2? cc @AntonioFilipov

**Comment by lgayatri** [comment]
@sergiosagu @mdubya66 
Build: VIC RC3 : vic-v1.3.0-rc3-2784-7d227d5c.ova

Reopening the issue as I saw it again with RC3 build.

ESX host: w2-hs2-d2612 was rebooted and below screenshots are the inventory details.

Containers are here:
![image](https://user-images.githubusercontent.com/25006749/33792621-008b0c7c-dccb-11e7-98b4-68d4488b1703.png)

VCHs are:
![image](https://user-images.githubusercontent.com/25006749/33792630-0daab952-dccb-11e7-8daa-a6ea3392a2ab.png)

After reboot, the ESX host came up normally and so the VCHs. Admiral still shows them in OFF state.
U-VIC-0001 is 10.197.37.133
![image](https://user-images.githubusercontent.com/25006749/33792808-cc554080-dccf-11e7-86a0-f246038e1f40.png)

Re-scanned but still the same result.

**Comment by lgayatri** [comment]
Its been more than 3 hours now and I still see the UI showing these hosts as OFF.

**Comment by lgayatri** [comment]
[xenonHost.0.zip](https://github.com/vmware/vic/files/1544499/xenonHost.0.zip) Attaching admiral log. Setup may not be in the same state as other tests are going on.

**Comment by mdubya66** [comment]
To confirm, docker ps -a shows the containers are in the expected state?

**Comment by lgayatri** [comment]
docker -H tcp://10.197.37.133:2376 --tls ps -a
Cannot connect to the Docker daemon at tcp://10.197.37.133:2376. Is the docker daemon running?

**Comment by mdubya66** [comment]
marking this as a potential ship stopper. it needs investigation. assigning to sflxn. @mhagen-vmware @mlh78750

**Comment by mdubya66** [comment]
133 is not responding to the docker client but when I first logged in the vchadmin shows it being OK. After pulling the logs the vchadmin shows the portlayer being down.
[container-logs-133.zip](https://github.com/vmware/vic/files/1546024/container-logs-133.zip)


(mwilliamson) dubs:~ $ docker -H 10.197.37.133:2376 --tls info
Cannot connect to the Docker daemon at tcp://10.197.37.133:2376. Is the docker daemon running?

The portlayer log has a fatal error. I've attached the log bundle container-logs-133.zip

```
time="2017-12-10T19:52:57Z" level=info msg="Launching portlayer server pprof server on 127.0.0.1:6063"
time="2017-12-10T19:52:58Z" level=info msg="{Formatter:0xc4208600b0 Level:info Syslog:<nil>}"
Dec 10 2017 19:52:58.574Z INFO  op=19706.3: Creating directory [CPBU_2TB_01] U-VIC-0001_2/kvStores
Dec 10 2017 19:52:58.581Z INFO  op=19706.3: Datastore path is [CPBU_2TB_01] U-VIC-0001_2/kvStores
Dec 10 2017 19:52:58.977Z INFO  NewKeyValueStore(apiKV) restored 3 keys
Dec 10 2017 19:52:58.977Z INFO  Beginning initialization of portlayer exec component
Dec 10 2017 19:52:59.029Z INFO  Syncing container cache
Dec 10 2017 19:52:59.526Z WARN  skipping converting container VM VirtualMachine:vm-21159: could not parse id
Dec 10 2017 19:52:59.592Z INFO  op=19706.4: Creating directory [CPBU_2TB_01] U-VIC-0001_2/kvStores
Dec 10 2017 19:52:59.603Z INFO  op=19706.4: Datastore path is [CPBU_2TB_01] U-VIC-0001_2/kvStores
Dec 10 2017 19:52:59.616Z INFO  NewKeyValueStore(network.contexts.default) restored 0 keys
Dec 10 2017 19:53:00.231Z FATAL could not initialize port layer: could not find IP range
```

**Comment by mdubya66** [comment]
131 looks ok with 52 containers running. The port-layer logs from vchadmin does have some errors in it though. Attached as container-logs-131.zip

```
(mwilliamson) dubs:~ $ docker -H 10.197.37.131:2376 --tls info
Containers: 52
 Running: 52
 Paused: 0
 Stopped: 0
Images: 1
Server Version: v1.3.0-rc3-15260-19211b3
Storage Driver: vSphere Integrated Containers v1.3.0-rc3-15260-19211b3 Backend Engine
VolumeStores:
vSphere Integrated Containers v1.3.0-rc3-15260-19211b3 Backend Engine: RUNNING
…
```
[container-logs-131.zip](https://github.com/vmware/vic/files/1546026/container-logs-131.zip)

**Comment by mdubya66** [comment]
So this could be a different issue than the Eventual Consistency model admiral issue

**Comment by sergiosagu** [comment]
@AntonioFilipov - could you take a look at @lgayatri and @mdubya66 comments? thanks!

**Comment by AntonioFilipov** [comment]
Admiral relies on the host "info" command in order to check the availability of the host. If the daemon is not running we mark the host as powered OFF.

**Comment by sflxn** [comment]
This appears to be related to #6851.  @lgayatri In the future, to truly determine if it's Admiral or VIC engine, you  should look at the vsphere UI and see if the VCH appliance is running and try a docker command against it.

**Comment by mdubya66** [comment]
looks like admiral eventual consitancy model is fixed and is detecting a down VCH. I'm going to close this. The down VCH issue is tracked in #6851.
